%% 250-kW Grid-Connected PV Array
%
% This example shows a detailed model of a 250-kW PV array connected to a 25-kV grid via a three-phase converter.

% Copyright 2015 Hydro-Quebec, and The MathWorks, Inc.

%%
open_system('GridConnectedPVArray');

%% PV Array
%  
% The PV array consists of 86 parallel strings. Each string has 7 SunPower SPR-415E modules connected in series. Note that the model menu allows you to plot the I-V and P-V characteristics of the selected module or of the whole array.

%% Three-phase DC/AC Converter
%
% The converter is modeled using a 3-level IGBT bridge PWM-controlled. The inverter choke RL and a small harmonics filter C are used to filter the harmonics generated by the IGBT bridge.  A 250-kVA 250V/25kV three-phase transformer is used to connect the inverter to the utility distribution system.

%% Inverter Control
%
% The control system contains five major Simulink(R)-based subsystems:
% 
% * MPPT Controller:  The Maximum Power Point Tracking (MPPT) controller is based on the 'Perturb and Observe' technique. This MPPT system automatically varies the VDC reference signal of the inverter VDC regulator in order to obtain a DC voltage which will extract maximum power from the PV array.
% * VDC Regulator: Determine the required Id (active current) reference for the current regulator.
% * Current Regulator: Based on the current references Id and Iq (reactive current), the regulator determines the required reference voltages for the inverter. In our example, the Iq reference is set to zero.
% * PLL & Measurements: Required for synchronization and voltage/current
% measurements.
% * PWM Generator: Generate firing signals to the IGBTs based on the
% required reference voltages. In our example, the carrier frequency is set to 1980 Hz (33*60).
% 

%% Utility Grid
%
% The grid is modeled as a typical North American distribution grid. It included two 25-kV feeders, loads, grounding transformer and an equivalent 120-kV transmission system.

%% Simulation
%
% Run the simulation and observe the resulting signals on the various scopes.
%
% The initial input irradiance to the PV array model is 1000 W/m2 and the operating temperature is 45 degrees C. When steady-state is reached (around t=0.15 sec.), we get a PV voltage (Vdc_mean) of 481 V and the power extracted (Pdc_mean) from the array is 236 kW. These values correspond very well to the expected values from the PV module manufacturer specifications.
%
% At t=0.3 sec, sun irradiance is rapidly ramped down from 1000 W/m^2 to 200 W/m^2. Due to the MPPT operation, the control system reduces the VDC reference to 464 V in order to extract maximum power from the PV array (46 kW).

%%
